server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nirbkuma/SpringCloudConfig
          #username: uname
          #password: pass
          search-paths:
          - 'station*'
  security:
    user:
      name: khulja
      password: simsim               
